### ISSUE TITLE
Initial setting up

### ISSUE THREAD

**Issue by stephenstubbs** [LamaAni/PGXL-HELM#1]
I just want to say thank you again for this. What a great project. So I've cloned the it and run helm install postgresxl ./PGXL-HELM/

gtm is running fine however the other 3 I'm getting this error:
`PGXL:HELM: Port 6666 not available on postgresxl-postgres-xl-svc-gtm, retry in 1`

This is on a clean micro8s install and GKE cluster that I've tried it. I'm using helm 3 beta 3. Any idea what this could be?

**Comment by stephenstubbs** [comment]
Please disregard this. It was a networking issue in my clusters.

**Comment by LamaAni** [comment]
No prob. Also, I am adding a note about persistence. It is important to understand the nature of the boot sequence and how persistance is maintained between failures, downtime and reboots. If you want to keep the data forever please note that you must define a PersistantVolumeClaim. Will upload a new section to the Readme today. 

Also, if you find anything that dose not work out of the box, please make a note. I intend this to be hassle free for all the Jr. in my company :)

**Comment by stephenstubbs** [comment]
OK thank you. WIll definitely let you know. Will test this a lot. Getting it up and running was very easy. Haven't actually tried connecting to it yet from a client though but will get back to you as soon as I do.
