### ISSUE TITLE
Max Connections Discussion

### ISSUE THREAD

**Issue by stephenstubbs** [LamaAni/PGXL-HELM#18]
Hi,

Just wondering what your thoughts are on setting max_connections in the future. 

pgbouncer has a max_clent_connections which is how many connections it can receive and then max_db_connections which is how many it will hold to the coordinators if needed.

In my mind everything revolves around the coordinators so it would be great if possible to somehow set 2 variables something like the following.

coordinator_max_connections
pgbouncer_connection_ratio (1 meaning 1:1 connections anything more meaning that pgbouncer will keep clients waiting if needed)

then datanode max_connections = (amount of coordinators) x (coordinator max_connections)

pgbouncer max_db_connections = (amount of coordinators) x (coordinator max_connections) / (amount of pgbouncer instances)

pgbouncer max_client_conn = (amount of coordinators) x (coordinator max_connections) / (amount of pgbouncer instances) x pgbouncer_connection_ratio

Would this be possible in the future with helm or would safer defaults be the only way? if we can only use defaults then I suggest setting datanodes to a higher amount like 5000 so they won't cause issues. Coordinators to 100 and pgbouncer to 1000 client connections and 100 db_connections

**Comment by LamaAni** [comment]
In general you have the added config, which appends to the config file @ 
(edited)
```yaml
config:
  append: |
          # add stuff to append here.
```

I am not a fan of specialized configurations and believe that values should be set separately, with a help file attached. pgbouncer_connection_ratio is in my opinion a bad idea.

We can in general, add another separate config.append for datanodes and coordinators. That allow you to use the PostgreSQL configuration directly.

**Comment by stephenstubbs** [comment]
OK that makes sense. will the config.append replace values that are already there by default?

**Comment by LamaAni** [comment]
> OK that makes sense. will the config.append replace values that are already there by default?

Its should. If it dose no then we would have an issue with other parameters.

**Comment by stephenstubbs** [comment]
I've been trying it. Perhaps I am doing something wrong https://github.com/LamaAni/PGXL-HELM/pull/19

**Comment by LamaAni** [comment]
Sorry, my fault on this. I was not clear, 
```yaml
config:
  append: |
            # this is a config comment.
```

In general, inside the pod you will find a file called /config/config_append which is the printout of the pg full config appendage. This file will be appended to ~/storage/data/postgresql.conf.

I would also recommend separating your yaml from your bash. 

This happens in: https://github.com/LamaAni/PGXL-HELM/blob/master/scripts/initialize_postgres_db

In the lines:
```shell
  cat /config/pg_config_append >> "${PGDATA}/postgresql.conf"
  cat /config/config_append >> "${PGDATA}/postgresql.conf"
```

**Comment by stephenstubbs** [comment]
ok thanks a lot. Initially I thought having it all in the script would be easier to begin with. You right though having them in this adds line spacing and escaping issues. Will separate them.

**Comment by stephenstubbs** [comment]
Sorry for reopening this issue so late but I forgot to test this.

I've tried adding the lines

```
config:
  append: |
    max_connections = 200
```

and it is adding. However it also seems to be adding it to the gtm and crashing it. How can I specify this for different pod types for example I want to set 3 coordinators and 3 datanodes. coordinators will have 100 connections and datanodes will have (3 X 100) which will be 300.

**Comment by LamaAni** [comment]
Hi, I see, ok. I need to separate the gtm/proxy and datanode/coordinator for configs. This is a change but not a big one.

**Comment by stephenstubbs** [comment]
ok great

**Comment by stephenstubbs** [comment]
Can this issue be closed?
