### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by stephenstubbs** [LamaAni/PGXL-HELM#2]
Hi,

I have been running various setups to test this and works very well so far with adding new nodes and persistence between adding and removing. This is everything I was hoping would be possible with k8s thank you very much for this.

All the nodes need to connect to each other with trust however clients connecting to the coordinators should be authenticated in my opinion. With swarm this was handled via different networks but from my understanding k8s has one flat network. 

What I've been thinking of doing is using pgbouncer on the coordinators and enable auth in this on port 6432. Then I can set a network policy which blocks port 5432 to any other pods except these which means clients will need to connect to port 6432 and provide credentials.

What do you think of this? Would you be able to suggest an easy way to create a network policy that targets all of these?

**Comment by LamaAni** [comment]
Hi, 

That is very very interesting. Can you PR this in? Do you have examples (also PR those if possible)?
I will grab a look at auth, if its blocking your test progression, otherwise I prefer to leave that till the end of the first testing round since its always finiky to test. 

I also completely agree that security is a thing to be considered here. In my mind, I always add it last, since it removes the eternal quandary of "Is it me or the security"? 

Best
Zav

**Comment by stephenstubbs** [comment]
That makes a lot of sense to leave it until after everything else is working. Once I have hashicorp vault working properly for users then I can do this. In my current swarm test I setup credentials using swarm secrets and a small app I developed which sets up and rotates passwords for these users. However hashicorp vault is a million times better than the app I have done. I have an admin user, replication user used for slaves and a connection pool user used for pgbouncer. Then have a setup similar to this https://www.cybertec-postgresql.com/en/pgbouncer-authentication-made-easy/ which uses the connection pool user.

**Comment by LamaAni** [comment]
OK. Lets compare this to the recommended k8 by google. Pick the winner. This is awesome.

**Comment by LamaAni** [comment]
Added pr for superuser name and superuser password https://github.com/LamaAni/PGXL-HELM/pull/11

**Comment by stephenstubbs** [comment]
ok brilliant thanks will add a pr with the changed install.sh to work with this in this new branch. I have finished the pgbouncer-deployment. Just testing it and setting up 3 vault user creation policies one for pgbouncer which appends the pg_shadow lookup, one for superusers and one for readonly users. I think that should cover a lot of uses. People can add any other policies they want to the install script. Should I add a pr for this to the add_passwords branch or create a new pgbouncer branch based off of the add_passwords branch?

**Comment by stephenstubbs** [comment]
I've tried adding this to the install.sh like below:

```
POSTGRES_PASSWORD="your_password"

#=================================================================================================
# SETUP PGXL
#-------------------------------------------------------------------------------------------------
git clone --single-branch --branch add_passwords https://github.com/LamaAni/PGXL-HELM.git

# Setup secret for postgres user
BASE64_PASSWORD=$(printf "${POSTGRES_PASSWORD}" | base64)
sed -i "s/bGFtYQ==/${BASE64_PASSWORD}/g" PGXL-HELM/examples/deployments/with_password/pg_secrets.yaml
kubectl apply -f ./PGXL-HELM/examples/deployments/with_password/pg_secrets.yaml

helmfile sync # not sure what this is supposed to do as it isn't working for me
```
but not sure how to use this helmfile sync command in the readme and what it does. I will just finish the pgbouncer without this secret for now.. it's a minor change to the pgbouncer section to use this once I can get this working.

**Comment by stephenstubbs** [comment]
Is this the project that it's using? https://github.com/roboll/helmfile
Do I run it from within the PGXL-HELM folder?
Sorry I just want to be sure I don't mess up anything with this install script.

**Comment by LamaAni** [comment]
Hi, 

Its the correct helmfile project. 

For your new code, please create a branch. I am still thinking of whether vault is in the scope, but I think pg_bouncer definitely is. I am also thinking of switching the proxies to a deployment. Dose the pg_bouncer require persistence (data storage)? 

I can add more instruction on how to use the helmfile (including the link). Basically, its a way to use helm to deploy using a specific set of values.  I think your error is that you are not running it in the correct folder, i.e. 
```shell
kubectl apply -f ./PGXL-HELM/examples/deployments/with_password/pg_secrets.yaml
```
Tells me you are trying to apply from the root chart folder, while you should be running inside the example folder.


More info about the secret:

The secret, by itself, you must apply on your own with,
```shell
kubectl apply -f secret.yaml
```
Once the secret is identified, you need to set two values, 
```yaml
passwords_secret_name: [name defined in metadeta]
pg_password: [name of the key]
```
Then the chart will apply the secret to the pod. 

I know that helm has its secrets plugin but I am not integrating that into the chart. The helmfile secret can be applied automatically with the right helmfile configuration, but I am thinking of keeping it simple. If one wants to connect the helmfile deploy to the specific use case secret all they have to do is set the values above.

Once the secret is applied, to use helmfile, simply install it, then navigate to the directory where the hemlfile.yaml exists and run
```shell
helmfile sync
```
That should work.

**Comment by LamaAni** [comment]
For a complete script, note the difference is the folder path checks. The helmfile in the example uses
a relative path to find the chart and values file. (This can be replaced with a link to a release).

```yaml
    # To use a specific release, not directory sensitive, replace the chart value like so,
    # chart: https://github.com/LamaAni/PGXL-HELM/archive/0.5.0.tar.gz
    
    # currently using a relative path
    chart: ../../
    values:
      - ./values.yaml
```

```shell
#!/usr/bin/env bash

SECRETS_FILE="$1"
if [ -z "$SECRETS_FILE" ]; then
  echo "you must supply a secrets file."
  exit 2
fi

# Should be run in the appropriate folder.
if [ ! -f "./helmfile.yaml" ]; then
  echo "Error, must be run in a folder where there is a helmfile.yaml";
  exit 1
fi

if [ ! -f "$SECRETS_FILE" ]; then
  echo "Secrets file not found @ $SECRETS_FILE"
  exit 1
fi

kubectl apply -f $SECRETS_FILE || exit 1
helmfile sync || exit 1
```

**Comment by stephenstubbs** [comment]
ok thanks a lot for the help. Will try this. OK yes I get that vault might not be in the scope of this project. Will create two pgbouncer deployments. One with and one without vault. For my use case I want credentials for each pod generated automatically but it can just as easily be used with users created manually. It just won't be quite as automated. pgbouncer doesnt require persistence.

**Comment by stephenstubbs** [comment]
Here is the pr for a deployment of pgbouncer https://github.com/LamaAni/PGXL-HELM/pull/14. I'm not quite sure how you want to integrate it. Let me know if there is anything you want me to do with this.

**Comment by stephenstubbs** [comment]
pgbouncer 1.11 finally support scram-sha-256. Would be great at some point if we could use that rather than md5 as md5 isn't secure. I can do this if you want once I understand where you are setting the password for the superuser.

**Comment by LamaAni** [comment]
Hi,

Deployment merged (experimental is always allowed - which is why its marked with such heavy warnings).

If you want to change the md5 that is perfectly reasonable, but please add a value in the chart main values file with a default value of md5, under
```yaml
security.postgres_auth_type: md5
```
And add an environment variable to envs.yaml in templates. This auth type will replace the hardcoded 
```shell
-A "md5"
```

You can find the username and password configuration here: https://github.com/LamaAni/PGXL-HELM/blob/master/scripts/initialize_postgres_db

In this bit of code:
```shell
    echo "$LOGGING_PREFIX Database superuser password found, initializing db with password."
    PG_PW_FILE="/tmp/$(mktemp pgpass-XXXXX.pwd)"
    echo "${PGPASSWORD}" > "$PG_PW_FILE"

    initdb \
      -A "md5"\
      -D "${PGDATA}" \
      -U "${PGUSER}" \
      --nodename="${PG_NODE}" \
      --pwfile="${PG_PW_FILE}" || exit $?
```

Oh, and :) Dont foget the readme.

**Comment by sstubbs** [comment]
I guess this issue can be closed now unless you want to keep it open for reference. the pgbouncer install script should work for people.

They will be able to connect as the postgres user created and then run sql like the following:

```
# SETUP DYNAMIC CONNECTION POOL FUNCTION
LOOKUP_FUNCTION="
CREATE SCHEMA IF NOT EXISTS connection_pool;
GRANT USAGE ON SCHEMA connection_pool TO postgres;
CREATE OR REPLACE FUNCTION connection_pool.lookup (
   INOUT p_user     name,
   OUT   p_password text
) RETURNS record
   LANGUAGE sql SECURITY DEFINER SET search_path = pg_catalog AS
\$FUNC\$ SELECT usename, passwd FROM pg_shadow WHERE usename = p_user \$FUNC\$;
REVOKE EXECUTE ON FUNCTION connection_pool.lookup(name) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION connection_pool.lookup(name) TO postgres;
"
psql -d template1 -c "${LOOKUP_FUNCTION}" || true
psql -d postgres -c "${LOOKUP_FUNCTION}" || true
sleep 5
psql -c "CLEAN CONNECTION TO ALL FOR template1;" 
```
Let me know if you want me to do anything else with this and if/how you want integrate it directly into the chart iteself. Will get the install script with vault done next which is what I'll be using. I will run this sql via vaults role creation_statements.

**Comment by stephenstubbs** [comment]
I guess this issue can be closed now unless you want to keep it open for reference. the pgbouncer install script should work for people.

They will be able to connect as the postgres user created and then run sql like the following:

```
# SETUP DYNAMIC CONNECTION POOL FUNCTION
LOOKUP_FUNCTION="
CREATE SCHEMA IF NOT EXISTS connection_pool;
GRANT USAGE ON SCHEMA connection_pool TO postgres;
CREATE OR REPLACE FUNCTION connection_pool.lookup (
   INOUT p_user     name,
   OUT   p_password text
) RETURNS record
   LANGUAGE sql SECURITY DEFINER SET search_path = pg_catalog AS
\$FUNC\$ SELECT usename, passwd FROM pg_shadow WHERE usename = p_user \$FUNC\$;
REVOKE EXECUTE ON FUNCTION connection_pool.lookup(name) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION connection_pool.lookup(name) TO postgres;
"
psql -d template1 -c "${LOOKUP_FUNCTION}" || true
psql -d postgres -c "${LOOKUP_FUNCTION}" || true
sleep 5
psql -c "CLEAN CONNECTION TO ALL FOR template1;" 
```
Let me know if you want me to do anything else with this and if/how you want integrate it directly into the chart. Will get the install script with vault done next which is what I'll be using. I will run this sql via vaults role creation_statements.

**Comment by LamaAni** [comment]
Hi, lets keep this open for now. 
I will close it in a few weeks if we find no changes.

**Comment by stephenstubbs** [comment]
ok sounds good
