### ISSUE TITLE
Examples Not Working

### ISSUE THREAD

**Issue by stephenstubbs** [LamaAni/PGXL-HELM#22]
I've been using the with_user example which works fine. I've been checking the other two and with both of them the coordinators seem to get stuck wating on the datanodes.

**Comment by LamaAni** [comment]
Will check on this asap and see.

**Comment by LamaAni** [comment]
Hi, I cannot reproduce. All samples are working. 
Please make sure to re-pull master. 
If you try again and it dose not succeed can you please post your actions so I can reproduce?

**Comment by stephenstubbs** [comment]
thanks sure will do

**Comment by stephenstubbs** [comment]
While testing it on microk8s on my dev machine which has 4 cores it only seems to work if the combination of coordinators and datanodes is 4 or less.

I see under the resources section there is a default of 1 cpu per pod so this makes sense why it's not working. If this is the case perhaps set the detault to 2 coordinators and 2 datanodes? As quite a lot of people haven't got more than 4 core cpus and might think this project doesn't work in their dev environment. If you want to leave it as 2 and 4 no problem but just an idea.

**Comment by LamaAni** [comment]
Ha, I see. I work on a google cluster. 

In this case I would prefer to change the cpu requests to 250m, this should be enough for most operations inside the db and would not take too many resources. 

Will send a PR soon.

**Comment by LamaAni** [comment]
@sstubbs 

Please see PR: https://github.com/LamaAni/PGXL-HELM/pull/24/files

If you could check this that would be awesome.

**Comment by stephenstubbs** [comment]
OK I've tested it and it runs well. Thanks a lot. I tend to try everything locally that I can before testing it on staging to try and understand what is going on.

**Comment by stephenstubbs** [comment]
Oh and just to say I've tested it with 8 coordinators and 8 datanodes on a i7 6700k with 64 GB of RAM. Starts up very fast and all nodes are added correctly. Very impressed with this.

**Comment by LamaAni** [comment]
Awesome. I would be very interested to know if there is a difference, mainly in indexing, when switching to a lower CPU. I would assume that is the case.

Also, I wonder if the default values for this should be changed. Right now I am tending towards no. But if we could run benchmarks in parallel then maybe that would give us a better estimation of the minimal resources required. 

I would love to have benchmarks for:
1. Indexing.
2. Copy into pg.
3. Copy from pg. 
4. Joins.

**Comment by LamaAni** [comment]
I will keep this issue alive since others might encounter the same thing, with difference resource requirements.

**Comment by stephenstubbs** [comment]
OK will get some benchmarks done on two dev machines and on staging cluster once everything is up and running. To be honest I don't really do much benchmarking. Should I use pgbench?

**Comment by stephenstubbs** [comment]
Usually I just use analyze on queries that need optimisation but it would be good to have a standard set of benchmarking tests that are run.

**Comment by LamaAni** [comment]
The analyze is estimation usually. I have not benchmarked any pg before and would have to read about it.  I think I would be able to do this only nearing the end of the week... so might be a bit.

Please do post anything you find....

**Comment by stephenstubbs** [comment]
ok will let you know what I find.

**Comment by stephenstubbs** [comment]
Can this be closed? I have added a new bechmarking ticket.
