### ISSUE TITLE
User Credentials - Vault discussions

### ISSUE THREAD

**Issue by stephenstubbs** [LamaAni/PGXL-HELM#3]
I am in the process of setting up hashicorp vault to work with this so credentials can be stored, rotated and provided to other pods. Is this support something you would like to add to this chart?

**Comment by LamaAni** [comment]
I am not familiar. Can you PR this in? I would be also very interested to see how you integrated it any either pull it in or make it easier to integrate.

**Comment by stephenstubbs** [comment]
OK great will do a PR once done. Still getting it working.

**Comment by stephenstubbs** [comment]
I've been trying different approaches to getting vault installed which will work well with pgbouncer. Here is the initial setup of vault and pgxl together done by bash script based on this https://medium.com/@gmaliar/dynamic-secrets-on-kubernetes-pods-using-vault-35d9094d169 I've added a pull request here https://github.com/LamaAni/PGXL-HELM/pull/6 so you can see how it works.

What is nice about this is I can then setup pgbouncer with dynamic generated credentials. Let me know if this is something you are interesed in and how you would like to integrate this. Then any other pod which needs access can also generate its own credentials and its endpoint will be the pgbouncer one which will lookup the details via pg_shadow.

Will start working on the pgbouncer side of things now and see if it does in fact work as I think it will.

**Comment by stephenstubbs** [comment]
In line 65 of the install.sh I am using` connection_url="postgresql://postgres@${PGXL_NAME}-postgres-xl-svc:5432/postgres?sslmode=disable"` as we are not setting up a root user so postgres has no password which isn't ideal. Would be nice if the helm chart was able to setup the initial user for this use like
`helm install stable/postgresql --set postgresUser=root,postgresPassword=root,postgresDatabase=rails_development`

**Comment by LamaAni** [comment]
Hi
Agreed on the username and password. I am preparing a secrets example of how to add that and would make sure the chart supports that. 

I will grab a look at both vault and pgbouncer but it could take a few days. There is some urgency at work. 

You mind if I move your examples into appropriate directories?

For pgbouncer, since we can increase the number of coordinators I would assume this is for the case where the db is supposed to accept thousands of connections and we want to keep coordinator memory low? If this is the case, and I understand the role correctly, I will add pgbouncer in between the coordinator and the service as another StatefulSet that can be increased, with an enabled switch. The bouncer will be its own pod.

**Comment by stephenstubbs** [comment]
Yes sure move them and take your time. Like I said I'm very new to k8s and just trying to get something working for my use and if I can help at all with this even better as it really is an amazing project.

Yes pgbouncer is for memory and latency reduction as opening a connection also takes more time than using a pooled one but the main reason for adding it here is so that authentication works properly. I can't think of another way on a flat network like k8s uses as we need a trust policy on pgxl nodes. Once I have a working example we can see whether it works as expected. I'm sure there are many ways to sort out this auth problem but this adds performance too so should be a good attempt.

Then the last step would be adding a network policy to disallow access to pgxl nodes from any other pod except themselves and pgbouncer. Then clients just connect directly to pgbouncer. Actually I guess via putting it between the coordinators and the service like you suggest might actually do this anyway.

Thats a great idea to add it between the service and the coordinator if enabled by a switch. Ideally from a performance perspective it should actually be installed on each coordinator and connect via a unix socket but I think having it in a different pod like you suggest makes more sense as it can be scaled separately.

**Comment by LamaAni** [comment]
Vault folder changes PR. 

https://github.com/LamaAni/PGXL-HELM/pull/7/files
