### ISSUE TITLE
Load Balancing

### ISSUE THREAD

**Issue by stephenstubbs** [LamaAni/PGXL-HELM#4]
Sorry for all the questions I'm new to k8s. With swarm I was using a separate haproxy container which load balanced between coordinators. Is there some sort of generic way to do this in k8s or should I look at istio specifically seeing as that's what I'm using?

**Comment by LamaAni** [comment]
I am using the LoadBalacer service as the point of connection. See https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer 

That would do most of the work. If you find issues with it, I do not mind adding more options for load balancing, but first I wanna make sure we are not adding things that are not needed.

Also, ;) As always, any test that you do and can PR in that will be awsome.

**Comment by stephenstubbs** [comment]
OK great thanks will have a look at that :)

**Comment by LamaAni** [comment]
Hi, sorry, something went wrong with my config. It seems that the pods are using a ClusterIP rather then a LoadBalancer service. 

I will fix that soon and PR it in.

**Comment by LamaAni** [comment]
PR is up. See here: https://github.com/LamaAni/PGXL-HELM/pull/5

**Comment by stephenstubbs** [comment]
Great thanks. Yes its working well now. This can be closed.
