### ISSUE TITLE
Planned release - 0.8.0

### ISSUE THREAD

**Issue by LamaAni** [LamaAni/PGXL-HELM#48]
### What:

1. Changes to structure. 
2. Init files and startup files.
3. Updates to readme.

### Bug fixes:
1. long names,
2. Separate configurations for each node. (max_connections bug)

### Experimental
1. pg_bouncer init scripts.
2. vault scripts.

**Comment by stephenstubbs** [comment]
looks good to me. Anything you want me to do with this?

**Comment by LamaAni** [comment]
@sstubbs Anything you wanna add to this release? Anything we did that is not in here? 
If you could fix the readme that would be amazing, my grammar is not that good anyways. 

I want to do another cleanup of the templates, scripts, experimental and examples, add some readmes and send that PR. After this I think you will have a version you can take to staging and test there, so we can get some real world usage outside of my own tests (and dev db).

**Comment by LamaAni** [comment]
Also, should we add the benchmarks to the release?

**Comment by stephenstubbs** [comment]
ok sounds good. I think we should wait until the issues I have posted about the benchmarks have some response as those errors even if they aren't breaking anything are a problem. I will go through the readme now and also the experimental and cleanup anything I've missed. Will also do readme files for all the experimental folders. The max_connections issue I've just reopened https://github.com/LamaAni/postgres-xl-helm/issues/18 will be a problem for me in testing I'm sure but it can wait until the next release if it's a big problem to fix.

**Comment by LamaAni** [comment]
OK. Benchmarks out then. Next release.

**Comment by LamaAni** [comment]
Update to include bug https://github.com/LamaAni/postgres-xl-helm/issues/18

**Comment by stephenstubbs** [comment]
testing this issue https://github.com/LamaAni/postgres-xl-helm/issues/44 today on gke and will let you know what I find. I've added a bit more cleanup with this pr https://github.com/LamaAni/postgres-xl-helm/pull/53

Once you happy with these can this version be released? Then I can start testing it.

**Comment by LamaAni** [comment]
Fantastic. Checking PR asap.

**Comment by LamaAni** [comment]
Version has been release. Closing issue.
