### ISSUE TITLE
mac os replace_with_env bug

### ISSUE THREAD

**Issue by stephenstubbs** [LamaAni/PGXL-HELM#54]
Having an issue with the variable in templates not being replaced on mac os using 

```
function replace_with_env() {
  # replace any {{ENV_NAME}} with its respective env value.
  value="$1"

  # the regular expression matches {{ [SOME NAME] }}
  re='(.*)\{\{\s*(\w+)\s*\}\}(.*)'

  # search for all replacements.
  while [[ "$value" =~ $re ]]; do
    env_name=${BASH_REMATCH[2]}
    value="${BASH_REMATCH[1]}${!env_name}${BASH_REMATCH[3]}"
  done

  echo "$value"
}
```

in the experimental install files.

changing it to

```
function replace_with_env() {
  # replace any {{ENV_NAME}} with its respective env value.
  str="$1"

  while [[ $str =~ ('{{'([[:alnum:]_]+)'}}') ]]; do
      str=${str//${BASH_REMATCH[1]}/${!BASH_REMATCH[2]}}
  done

  echo "$str"
}
```
works

Will do some more testing in a few days when I'm back on my linux machine but I might be changing all occurrences of this function in experimental to this if it works on linux and mac os.

**Comment by LamaAni** [comment]
Whats the bash version? I think this is a bash legacy issue. I have seen this happens on macs. I general I have no issue with replacing that script. 

@sstubbs Do you need this in the release?

**Comment by stephenstubbs** [comment]
My bash version is 3.2.57(1)-release in the standard catalina terminal. OK great I will test it works now then in an ubuntu vm. If it does I'll change occurences of this function in a pr. If possible it would be great if this is included in the release.

**Comment by LamaAni** [comment]
Hi yea, that would make sense. Current bash version is 5, so it is a far behind. 
Not sure what the issue is though, it should work on both. 

That said, both are valid bash syntax and should work. So, just pr it in.
