### ISSUE TITLE
incomplete startup packet on datanode

### ISSUE THREAD

**Issue by stephenstubbs** [LamaAni/PGXL-HELM#57]
I have a continual error being generated in the datanode logs. It is working fine but perhaps this has something to do with the polling from other nodes?

**Comment by LamaAni** [comment]
If the error is the repeating "incomplete startup packet" it can be ignored. See here: https://dba.stackexchange.com/questions/87622/postgres-incomplete-startup-packet-error
It would happen when the connection exits. 

I general please show the error and write a reproduce procedure if possible. I will add bug and feature templates to the issues.

**Comment by stephenstubbs** [comment]
OK great I see the new bug report template. WIll do a few different  deploys to find the issue and then create a new issue using that. This can be closed if its ok with you.
