### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by stephenstubbs** [LamaAni/PGXL-HELM#66]
**Describe the bug**
The line `nc -zv "$node_host" $PG_PORT &> /dev/null` in `check_nodes_connection` was creating errors in datanode logs. Not breaking anything but a minor issue. I've changed it to `pg_isready -h "$node_host" -p "$PG_PORT" &> /dev/null` in the operator. Just so you know if you run into this.

**To Reproduce**
1. Create any cluster and watch any datanode logs
2. See error

**Comment by LamaAni** [comment]
Hi,

Can you post the log?

Tnx!

**Comment by stephenstubbs** [comment]
Every few seconds this will be seen on the datanode

```
 2020-02-23 15:10:06.642 UTC [150] LOG:  incomplete startup packet                                                                                                                                                                                                            │
│ 2020-02-23 15:10:11.650 UTC [161] LOG:  incomplete startup packet                                                                                                                                                                                                            │
│ 2020-02-23 15:10:16.656 UTC [172] LOG:  incomplete startup packet 
```

**Comment by stephenstubbs** [comment]
another similar issue is `Expecting a startup message, but received �` being shown in the gtm. This is an issue with using netcat for the gtm  which can be resolved using pgxc monitor https://github.com/pavouk-0/postgres-xl-docker/blob/f38112b3657165dcd36b7fc21192103aa0d063aa/bin/docker-healthcheck-gtm however this only seems to happen on startup and doesnt keep filling up the logs so I haven't changed this for now.

**Comment by LamaAni** [comment]
Hi, 

Yes you are correct, the reason is that the startup packet (or statup command) used though netcat is empty.

I like the use of `pg_isready`. If you have time a PR that would be amazing, otherwise I will do the pr in a few weeks and send the PR back. Since this is just a log dump, It is not urgent?

Best
Zav

**Comment by stephenstubbs** [comment]
Yes it's not an urgent issue at all. I'll do a PR for it as soon as I can.

**Comment by stephenstubbs** [comment]
Here is the pr to fix the issue with the datanodes
https://github.com/LamaAni/postgres-xl-helm/pull/67

This is the biggest problem as it keeps filling up the logs. I tried changing the gtm and proxy checks to use pgxc_monitor like https://github.com/pavouk-0/postgres-xl-docker/blob/f38112b3657165dcd36b7fc21192103aa0d063aa/bin/docker-healthcheck-gtm but it doesn't seem to work. Those aren't really a problem though as it's just a once off.

**Comment by LamaAni** [comment]
merged
